version: "3.9"

services:
  ### PSIRA Backend Container ###########################
  psira-backend:
    networks:
      - frontend
      - backend
      - shiny
      - rstudio

  ### Caddy Server Container ##################################

  caddy:    
    networks:
      - frontend
      - backend
      - shiny
      - rstudio

  ### R-Studio Container #########################################
  rstudio:
    profiles: 
      - rstudio
    image: rocker/tidyverse:4
    build: ./rstudio
    restart: unless-stopped
    ports:
      - '8787:8787'
    volumes:
      - ${SHINY_APPS_PATH}:/home/${RSTUDIO_USER}/shiny_apps
    environment:
      - PASSWORD=${RSTUDIO_PASSWORD}
      - USER=${RSTUDIO_USER}
    networks:
      - rstudio

### Networks Setup ############################################

networks:
  rstudio:
    driver: "bridge"
