#!/bin/sh

date=$(date '+%Y-%m-%dT%H:%M:%S')
filename="psira-data-${date}.dump"

mkdir -p /backups/postgres
mkdir -p /backups/mongo

echo "Running psira backup... ${date}"

pg_dump --clean -h postgres -U "$POSTGRES_USER" -d "$POSTGRES_DB" > "/backups/postgres/${filename}"

mongodump --host mongo --archive > "/backups/mongo/${filename}"

echo "Finished running psira backup... ${date}"
