#!/bin/sh

echo "Running psira data restore..."

get_archive() {
    i=1
    selected_archive=""
    for archive in $1; do
        if [ $i -eq $2 ]; then
            selected_archive=$(basename "$archive")
            break
        fi
        i=$((i+1))
    done

    echo "$selected_archive"
}

postgres_archive="/backups/postgres"
mongo_archive="/backups/mongo"
valid_selection=false

i=1
for archive in $postgres_archive/*; do
    file=$(basename "$archive")
    echo "$i) $file"
    i=$((i+1))
done

while true; do
    read -p "Enter the index of the archive you want to restore: " selected_index

    selected_file=$(get_archive "$postgres_archive/*" "$selected_index")

    if [ -z "$selected_file" ]; then
        echo "Invalid selection."
    else
        break
    fi
done

if [ -f "${mongo_archive}/${selected_file}" ]; then
    psql -h postgres -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f "${postgres_archive}/${selected_file}"
    mongorestore --host mongo --drop --archive="${mongo_archive}/${selected_file}"
else
    echo "Mongo file does not exist!"
fi

echo "Finished running psira data restore!"
