FROM rocker/tidyverse:4

# Crear usuario solo si no existe
# RUN id -u psira >/dev/null 2>&1 || useradd -m -s /bin/bash psira

# Asignar/actualizar contraseña
# RUN echo "psira:rstudioPassword" | chpasswd

# Dar permisos sudo
# RUN usermod -aG sudo psira
